# Generated by Django 4.2.3 on 2023-07-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='idUser',
            new_name='id_user',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profileImg',
            new_name='profile_img',
        ),
    ]
