# Generated by Django 4.2.3 on 2023-07-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_iduser_profile_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='default-profile-img.png', upload_to='profile-imgs/'),
        ),
    ]
