# Generated by Django 4.2.3 on 2023-07-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='notification_images'),
        ),
    ]
