# Generated by Django 4.2.3 on 2023-07-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_notification_post_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post_image_url',
        ),
        migrations.AddField(
            model_name='profile',
            name='profilecover',
            field=models.ImageField(default='default-profile-cover.png', upload_to='profile_covers/'),
        ),
    ]
