# Generated by Django 4.2.3 on 2023-07-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
